export default [
    "JavaScript",
    "Ruby",
    "Ruby on Rails",
    "HTML",
    "CSS",
    "SASS",
    "NodeJS",
    "React",
    "MongoDB",
    "SQL",
    "NoSQL",
    "MySQL",
    "Active Record",
    "PostgreSQL",
    "Mongoose",
    "REST API",
    "Java",
    "C++",
    "Python",
    "Django",
    "Semantic UI",
    "Material UI",
    "Materialize CSS",
    "Tailwind CSS",
    "Express JS",
    "Frontend Development",
    "Backend Development",
    "Teaching",
    "Guide",
    "Problem Solving",
    "Stress Management",
    "Time Management",
    "Deployment",
    "Software Development",
    "Web Development",
    "Planning",
    "Angular",
    "JQuery",
    "VueJS",
    "DenoJS",
    "Rust",
    "Redux",
    "Github",
    "Algorithms",
    "Data Structure",
    "Testing",
    "Cryptography",
    "Command Line Interface",
    "Bootstrap",
    "Tech Ethics"
]