export default [
    "JavaScript",
    "TypeScript",
    "Ruby",
    "Ruby on Rails",
    "HTML",
    "CSS",
    "SASS",
    "NodeJS",
    "React",
    "GraphQL",
    "Hooks",
    "State Management",
    "MongoDB",
    "SQL",
    "NoSQL",
    "MySQL",
    "Active Record",
    "PostgreSQL",
    "Mongoose",
    "REST API",
    "Java",
    "C++",
    "C",
    "Docker",
    "Unix",
    "Linux",
    "Python",
    "Django",
    "Flask",
    "PHP",
    "Code Editor",
    "Semantic UI",
    "Material UI",
    "Materialize CSS",
    "Tailwind CSS",
    "Express JS",
    "Frontend Development",
    "Backend Development",
    "Full Stack Development",
    "Teaching",
    "Guide",
    "Problem Solving",
    "Stress Management",
    "Time Management",
    "Deployment",
    "Software Development",
    "Web Development",
    "Planning",
    "Angular",
    "JQuery",
    "VueJS",
    "DenoJS",
    "Rust",
    "Redux",
    "Git",
    "Github",
    "Version Control",
    "Algorithms",
    "Data Structure",
    "Testing",
    "DevOps",
    "Cryptography",
    "Command Line Interface",
    "Bootstrap",
    "Tech Ethics",
    "Non-Technical",
    "Technical Interview",
    "Job Search",
    "Content Management System",
    "Web Sockets",
    "Machine Learning",
    "Data Science",
    "Caching",
    "Project Ideas"
]